name: test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print a file
        run: echo vineel
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print a name
        run: echo f1














        '
