name: vineel
on: push
jobs:
  build:
   runs-on: ubuntu-22.04
   steps:
     - run: echo building
  testing:
    runs-on: ubuntu-22.04
    steps:
      - run: echo testing
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - run: echo deploy
      
