
name: 
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run if or
        if: github.actor == 'kudipudivineel' || github.actor  == 'ddevsec-blip'
        run: echo "triggered"
