name: test-1
on: push
jobs:
  test-context:
    runs-on: ubuntu-latest
    steps:
      - name: using context variable
        run: |
          echo "this work is trigger ${{github.actor}}"
          echo "this repo name ${{github.repository}}"
